- name: Make sure Python2 is available
  hosts: idp
  become: True
  gather_facts: False
  tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Gather OS specific variables
  hosts: idp
  become: True
  gather_facts: True
  tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - "group_vars/distributions/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
        - "group_vars/distributions/{{ ansible_distribution }}.yml"
      tags: vars

- name: Install eduroam Identity Provider
  hosts: idp
  become: True
  gather_facts: True
  vars_files:
    - group_vars/secrets.yml
  roles:
    - freeradius
    - { role: eapol_test, when: play_eapol == True }
    
  handlers:
    - name: restart freeradius
      service: name={{ radius.name }} state=restarted
